<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="FullRun" duration-ms="96378" started-at="2018-09-25T17:37:31Z" finished-at="2018-09-25T17:39:07Z">
    <groups>
    </groups>
    <test name="Regression" duration-ms="96378" started-at="2018-09-25T17:37:31Z" finished-at="2018-09-25T17:39:07Z">
      <class name="automationframework.PerformanceTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:automationframework.PerformanceTest@224edc67]" name="beforeMethod" is-config="true" duration-ms="2971" started-at="2018-09-25T17:38:18Z" finished-at="2018-09-25T17:38:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="contactPage()[pri:0, instance:automationframework.PerformanceTest@224edc67]" name="contactPage" duration-ms="19664" started-at="2018-09-25T17:38:21Z" finished-at="2018-09-25T17:38:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Page is too slow the page took 19 the pass criteria is less than 10 seconds expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Page is too slow the page took 19 the pass criteria is less than 10 seconds expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at automationframework.PerformanceTest.performanceTest(PerformanceTest.java:67)
at automationframework.PerformanceTest.contactPage(PerformanceTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactPage -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:automationframework.PerformanceTest@224edc67]" name="afterMethod" is-config="true" duration-ms="709" started-at="2018-09-25T17:38:40Z" finished-at="2018-09-25T17:38:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:automationframework.PerformanceTest@224edc67]" name="beforeMethod" is-config="true" duration-ms="2626" started-at="2018-09-25T17:38:41Z" finished-at="2018-09-25T17:38:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="homePage()[pri:0, instance:automationframework.PerformanceTest@224edc67]" name="homePage" duration-ms="22503" started-at="2018-09-25T17:38:44Z" finished-at="2018-09-25T17:39:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Page is too slow the page took 22 the pass criteria is less than 10 seconds expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Page is too slow the page took 22 the pass criteria is less than 10 seconds expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at automationframework.PerformanceTest.performanceTest(PerformanceTest.java:67)
at automationframework.PerformanceTest.homePage(PerformanceTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePage -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:automationframework.PerformanceTest@224edc67]" name="afterMethod" is-config="true" duration-ms="669" started-at="2018-09-25T17:39:06Z" finished-at="2018-09-25T17:39:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- automationframework.PerformanceTest -->
      <class name="automationframework.ContactPageValidation">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:automationframework.ContactPageValidation@4c70fda8]" name="beforeMethod" is-config="true" duration-ms="27205" started-at="2018-09-25T17:37:31Z" finished-at="2018-09-25T17:37:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="checkValidationMsg()[pri:0, instance:automationframework.ContactPageValidation@4c70fda8]" name="checkValidationMsg" duration-ms="663" started-at="2018-09-25T17:37:58Z" finished-at="2018-09-25T17:37:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkValidationMsg -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:automationframework.ContactPageValidation@4c70fda8]" name="afterMethod" is-config="true" duration-ms="2" started-at="2018-09-25T17:37:58Z" finished-at="2018-09-25T17:37:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:automationframework.ContactPageValidation@4c70fda8]" name="beforeMethod" is-config="true" duration-ms="18887" started-at="2018-09-25T17:37:58Z" finished-at="2018-09-25T17:38:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="inputValues()[pri:0, instance:automationframework.ContactPageValidation@4c70fda8]" name="inputValues" duration-ms="439" started-at="2018-09-25T17:38:17Z" finished-at="2018-09-25T17:38:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Validation Msg is appearing] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Validation Msg is appearing] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at automationframework.ContactPageValidation.inputValues(ContactPageValidation.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inputValues -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:automationframework.ContactPageValidation@4c70fda8]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-09-25T17:38:18Z" finished-at="2018-09-25T17:38:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- automationframework.ContactPageValidation -->
    </test> <!-- Regression -->
  </suite> <!-- FullRun -->
</testng-results>
